version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./src/models
        target: /models
    ports:
      - 8000:8000
      - 5900:5900
      - 5901:5901
      - 5902:5902
      - 5903:5903
    init: true
    restart: always
